-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('addressbook_pb')


local PERSON = protobuf.Descriptor();
local PERSON_PHONENUMBER = protobuf.Descriptor();
local PERSON_PHONENUMBER_NUMBER_FIELD = protobuf.FieldDescriptor();
local PERSON_PHONENUMBER_TYPE_FIELD = protobuf.FieldDescriptor();
local PERSON_PHONETYPE = protobuf.EnumDescriptor();
local PERSON_PHONETYPE_MOBILE_ENUM = protobuf.EnumValueDescriptor();
local PERSON_PHONETYPE_HOME_ENUM = protobuf.EnumValueDescriptor();
local PERSON_PHONETYPE_WORK_ENUM = protobuf.EnumValueDescriptor();
local PERSON_NAME_FIELD = protobuf.FieldDescriptor();
local PERSON_ID_FIELD = protobuf.FieldDescriptor();
local PERSON_EMAIL_FIELD = protobuf.FieldDescriptor();
local PERSON_PHONE_FIELD = protobuf.FieldDescriptor();
local PERSON_TINT32_FIELD = protobuf.FieldDescriptor();
local PERSON_TINT64_FIELD = protobuf.FieldDescriptor();
local PERSON_TUINT32_FIELD = protobuf.FieldDescriptor();
local PERSON_TUINT64_FIELD = protobuf.FieldDescriptor();
local PERSON_TSINT32_FIELD = protobuf.FieldDescriptor();
local PERSON_TSINT64_FIELD = protobuf.FieldDescriptor();
local PERSON_TBOOL_FIELD = protobuf.FieldDescriptor();
local PERSON_TFIXED64_FIELD = protobuf.FieldDescriptor();
local PERSON_TSFIXED64_FIELD = protobuf.FieldDescriptor();
local PERSON_TDOUBLE_FIELD = protobuf.FieldDescriptor();
local PERSON_TFIXED32_FIELD = protobuf.FieldDescriptor();
local PERSON_TSFIXED32_FIELD = protobuf.FieldDescriptor();
local PERSON_TFLOAT_FIELD = protobuf.FieldDescriptor();
local ADDRESSBOOK = protobuf.Descriptor();
local ADDRESSBOOK_PERSON_FIELD = protobuf.FieldDescriptor();

PERSON_PHONENUMBER_NUMBER_FIELD.name = "number"
PERSON_PHONENUMBER_NUMBER_FIELD.full_name = ".tutorial.Person.PhoneNumber.number"
PERSON_PHONENUMBER_NUMBER_FIELD.number = 1
PERSON_PHONENUMBER_NUMBER_FIELD.index = 0
PERSON_PHONENUMBER_NUMBER_FIELD.label = 2
PERSON_PHONENUMBER_NUMBER_FIELD.has_default_value = false
PERSON_PHONENUMBER_NUMBER_FIELD.default_value = ""
PERSON_PHONENUMBER_NUMBER_FIELD.type = 9
PERSON_PHONENUMBER_NUMBER_FIELD.cpp_type = 9

PERSON_PHONENUMBER_TYPE_FIELD.name = "type"
PERSON_PHONENUMBER_TYPE_FIELD.full_name = ".tutorial.Person.PhoneNumber.type"
PERSON_PHONENUMBER_TYPE_FIELD.number = 2
PERSON_PHONENUMBER_TYPE_FIELD.index = 1
PERSON_PHONENUMBER_TYPE_FIELD.label = 1
PERSON_PHONENUMBER_TYPE_FIELD.has_default_value = true
PERSON_PHONENUMBER_TYPE_FIELD.default_value = HOME
PERSON_PHONENUMBER_TYPE_FIELD.enum_type = _PERSON_PHONETYPE
PERSON_PHONENUMBER_TYPE_FIELD.type = 14
PERSON_PHONENUMBER_TYPE_FIELD.cpp_type = 8

PERSON_PHONENUMBER.name = "PhoneNumber"
PERSON_PHONENUMBER.full_name = ".tutorial.Person.PhoneNumber"
PERSON_PHONENUMBER.nested_types = {}
PERSON_PHONENUMBER.enum_types = {}
PERSON_PHONENUMBER.fields = {PERSON_PHONENUMBER_NUMBER_FIELD, PERSON_PHONENUMBER_TYPE_FIELD}
PERSON_PHONENUMBER.is_extendable = false
PERSON_PHONENUMBER.extensions = {}
PERSON_PHONENUMBER.containing_type = PERSON
PERSON_PHONETYPE_MOBILE_ENUM.name = "MOBILE"
PERSON_PHONETYPE_MOBILE_ENUM.index = 0
PERSON_PHONETYPE_MOBILE_ENUM.number = 0
PERSON_PHONETYPE_HOME_ENUM.name = "HOME"
PERSON_PHONETYPE_HOME_ENUM.index = 1
PERSON_PHONETYPE_HOME_ENUM.number = 1
PERSON_PHONETYPE_WORK_ENUM.name = "WORK"
PERSON_PHONETYPE_WORK_ENUM.index = 2
PERSON_PHONETYPE_WORK_ENUM.number = 2
PERSON_PHONETYPE.name = "PhoneType"
PERSON_PHONETYPE.full_name = ".tutorial.Person.PhoneType"
PERSON_PHONETYPE.values = {PERSON_PHONETYPE_MOBILE_ENUM,PERSON_PHONETYPE_HOME_ENUM,PERSON_PHONETYPE_WORK_ENUM}
PERSON_NAME_FIELD.name = "name"
PERSON_NAME_FIELD.full_name = ".tutorial.Person.name"
PERSON_NAME_FIELD.number = 1
PERSON_NAME_FIELD.index = 0
PERSON_NAME_FIELD.label = 2
PERSON_NAME_FIELD.has_default_value = false
PERSON_NAME_FIELD.default_value = ""
PERSON_NAME_FIELD.type = 9
PERSON_NAME_FIELD.cpp_type = 9

PERSON_ID_FIELD.name = "id"
PERSON_ID_FIELD.full_name = ".tutorial.Person.id"
PERSON_ID_FIELD.number = 2
PERSON_ID_FIELD.index = 1
PERSON_ID_FIELD.label = 2
PERSON_ID_FIELD.has_default_value = false
PERSON_ID_FIELD.default_value = 0
PERSON_ID_FIELD.type = 3
PERSON_ID_FIELD.cpp_type = 2

PERSON_EMAIL_FIELD.name = "email"
PERSON_EMAIL_FIELD.full_name = ".tutorial.Person.email"
PERSON_EMAIL_FIELD.number = 3
PERSON_EMAIL_FIELD.index = 2
PERSON_EMAIL_FIELD.label = 1
PERSON_EMAIL_FIELD.has_default_value = false
PERSON_EMAIL_FIELD.default_value = ""
PERSON_EMAIL_FIELD.type = 9
PERSON_EMAIL_FIELD.cpp_type = 9

PERSON_PHONE_FIELD.name = "phone"
PERSON_PHONE_FIELD.full_name = ".tutorial.Person.phone"
PERSON_PHONE_FIELD.number = 4
PERSON_PHONE_FIELD.index = 3
PERSON_PHONE_FIELD.label = 3
PERSON_PHONE_FIELD.has_default_value = false
PERSON_PHONE_FIELD.default_value = {}
PERSON_PHONE_FIELD.message_type = PERSON_PHONENUMBER
PERSON_PHONE_FIELD.type = 11
PERSON_PHONE_FIELD.cpp_type = 10

PERSON_TINT32_FIELD.name = "tint32"
PERSON_TINT32_FIELD.full_name = ".tutorial.Person.tint32"
PERSON_TINT32_FIELD.number = 5
PERSON_TINT32_FIELD.index = 4
PERSON_TINT32_FIELD.label = 2
PERSON_TINT32_FIELD.has_default_value = false
PERSON_TINT32_FIELD.default_value = 0
PERSON_TINT32_FIELD.type = 5
PERSON_TINT32_FIELD.cpp_type = 1

PERSON_TINT64_FIELD.name = "tint64"
PERSON_TINT64_FIELD.full_name = ".tutorial.Person.tint64"
PERSON_TINT64_FIELD.number = 6
PERSON_TINT64_FIELD.index = 5
PERSON_TINT64_FIELD.label = 2
PERSON_TINT64_FIELD.has_default_value = false
PERSON_TINT64_FIELD.default_value = 0
PERSON_TINT64_FIELD.type = 3
PERSON_TINT64_FIELD.cpp_type = 2

PERSON_TUINT32_FIELD.name = "tuint32"
PERSON_TUINT32_FIELD.full_name = ".tutorial.Person.tuint32"
PERSON_TUINT32_FIELD.number = 7
PERSON_TUINT32_FIELD.index = 6
PERSON_TUINT32_FIELD.label = 2
PERSON_TUINT32_FIELD.has_default_value = false
PERSON_TUINT32_FIELD.default_value = 0
PERSON_TUINT32_FIELD.type = 13
PERSON_TUINT32_FIELD.cpp_type = 3

PERSON_TUINT64_FIELD.name = "tuint64"
PERSON_TUINT64_FIELD.full_name = ".tutorial.Person.tuint64"
PERSON_TUINT64_FIELD.number = 8
PERSON_TUINT64_FIELD.index = 7
PERSON_TUINT64_FIELD.label = 2
PERSON_TUINT64_FIELD.has_default_value = false
PERSON_TUINT64_FIELD.default_value = 0
PERSON_TUINT64_FIELD.type = 4
PERSON_TUINT64_FIELD.cpp_type = 4

PERSON_TSINT32_FIELD.name = "tsint32"
PERSON_TSINT32_FIELD.full_name = ".tutorial.Person.tsint32"
PERSON_TSINT32_FIELD.number = 9
PERSON_TSINT32_FIELD.index = 8
PERSON_TSINT32_FIELD.label = 2
PERSON_TSINT32_FIELD.has_default_value = false
PERSON_TSINT32_FIELD.default_value = 0
PERSON_TSINT32_FIELD.type = 17
PERSON_TSINT32_FIELD.cpp_type = 1

PERSON_TSINT64_FIELD.name = "tsint64"
PERSON_TSINT64_FIELD.full_name = ".tutorial.Person.tsint64"
PERSON_TSINT64_FIELD.number = 10
PERSON_TSINT64_FIELD.index = 9
PERSON_TSINT64_FIELD.label = 2
PERSON_TSINT64_FIELD.has_default_value = false
PERSON_TSINT64_FIELD.default_value = 0
PERSON_TSINT64_FIELD.type = 18
PERSON_TSINT64_FIELD.cpp_type = 2

PERSON_TBOOL_FIELD.name = "tbool"
PERSON_TBOOL_FIELD.full_name = ".tutorial.Person.tbool"
PERSON_TBOOL_FIELD.number = 11
PERSON_TBOOL_FIELD.index = 10
PERSON_TBOOL_FIELD.label = 2
PERSON_TBOOL_FIELD.has_default_value = false
PERSON_TBOOL_FIELD.default_value = false
PERSON_TBOOL_FIELD.type = 8
PERSON_TBOOL_FIELD.cpp_type = 7

PERSON_TFIXED64_FIELD.name = "tfixed64"
PERSON_TFIXED64_FIELD.full_name = ".tutorial.Person.tfixed64"
PERSON_TFIXED64_FIELD.number = 12
PERSON_TFIXED64_FIELD.index = 11
PERSON_TFIXED64_FIELD.label = 2
PERSON_TFIXED64_FIELD.has_default_value = false
PERSON_TFIXED64_FIELD.default_value = 0
PERSON_TFIXED64_FIELD.type = 6
PERSON_TFIXED64_FIELD.cpp_type = 4

PERSON_TSFIXED64_FIELD.name = "tsfixed64"
PERSON_TSFIXED64_FIELD.full_name = ".tutorial.Person.tsfixed64"
PERSON_TSFIXED64_FIELD.number = 13
PERSON_TSFIXED64_FIELD.index = 12
PERSON_TSFIXED64_FIELD.label = 2
PERSON_TSFIXED64_FIELD.has_default_value = false
PERSON_TSFIXED64_FIELD.default_value = 0
PERSON_TSFIXED64_FIELD.type = 16
PERSON_TSFIXED64_FIELD.cpp_type = 2

PERSON_TDOUBLE_FIELD.name = "tdouble"
PERSON_TDOUBLE_FIELD.full_name = ".tutorial.Person.tdouble"
PERSON_TDOUBLE_FIELD.number = 14
PERSON_TDOUBLE_FIELD.index = 13
PERSON_TDOUBLE_FIELD.label = 2
PERSON_TDOUBLE_FIELD.has_default_value = false
PERSON_TDOUBLE_FIELD.default_value = 0.0
PERSON_TDOUBLE_FIELD.type = 1
PERSON_TDOUBLE_FIELD.cpp_type = 5

PERSON_TFIXED32_FIELD.name = "tfixed32"
PERSON_TFIXED32_FIELD.full_name = ".tutorial.Person.tfixed32"
PERSON_TFIXED32_FIELD.number = 15
PERSON_TFIXED32_FIELD.index = 14
PERSON_TFIXED32_FIELD.label = 2
PERSON_TFIXED32_FIELD.has_default_value = false
PERSON_TFIXED32_FIELD.default_value = 0
PERSON_TFIXED32_FIELD.type = 7
PERSON_TFIXED32_FIELD.cpp_type = 3

PERSON_TSFIXED32_FIELD.name = "tsfixed32"
PERSON_TSFIXED32_FIELD.full_name = ".tutorial.Person.tsfixed32"
PERSON_TSFIXED32_FIELD.number = 16
PERSON_TSFIXED32_FIELD.index = 15
PERSON_TSFIXED32_FIELD.label = 2
PERSON_TSFIXED32_FIELD.has_default_value = false
PERSON_TSFIXED32_FIELD.default_value = 0
PERSON_TSFIXED32_FIELD.type = 15
PERSON_TSFIXED32_FIELD.cpp_type = 1

PERSON_TFLOAT_FIELD.name = "tfloat"
PERSON_TFLOAT_FIELD.full_name = ".tutorial.Person.tfloat"
PERSON_TFLOAT_FIELD.number = 17
PERSON_TFLOAT_FIELD.index = 16
PERSON_TFLOAT_FIELD.label = 2
PERSON_TFLOAT_FIELD.has_default_value = false
PERSON_TFLOAT_FIELD.default_value = 0.0
PERSON_TFLOAT_FIELD.type = 2
PERSON_TFLOAT_FIELD.cpp_type = 6

PERSON.name = "Person"
PERSON.full_name = ".tutorial.Person"
PERSON.nested_types = {PERSON_PHONENUMBER}
PERSON.enum_types = {PERSON_PHONETYPE}
PERSON.fields = {PERSON_NAME_FIELD, PERSON_ID_FIELD, PERSON_EMAIL_FIELD, PERSON_PHONE_FIELD, PERSON_TINT32_FIELD, PERSON_TINT64_FIELD, PERSON_TUINT32_FIELD, PERSON_TUINT64_FIELD, PERSON_TSINT32_FIELD, PERSON_TSINT64_FIELD, PERSON_TBOOL_FIELD, PERSON_TFIXED64_FIELD, PERSON_TSFIXED64_FIELD, PERSON_TDOUBLE_FIELD, PERSON_TFIXED32_FIELD, PERSON_TSFIXED32_FIELD, PERSON_TFLOAT_FIELD}
PERSON.is_extendable = false
PERSON.extensions = {}
ADDRESSBOOK_PERSON_FIELD.name = "person"
ADDRESSBOOK_PERSON_FIELD.full_name = ".tutorial.AddressBook.person"
ADDRESSBOOK_PERSON_FIELD.number = 1
ADDRESSBOOK_PERSON_FIELD.index = 0
ADDRESSBOOK_PERSON_FIELD.label = 3
ADDRESSBOOK_PERSON_FIELD.has_default_value = false
ADDRESSBOOK_PERSON_FIELD.default_value = {}
ADDRESSBOOK_PERSON_FIELD.message_type = PERSON
ADDRESSBOOK_PERSON_FIELD.type = 11
ADDRESSBOOK_PERSON_FIELD.cpp_type = 10

ADDRESSBOOK.name = "AddressBook"
ADDRESSBOOK.full_name = ".tutorial.AddressBook"
ADDRESSBOOK.nested_types = {}
ADDRESSBOOK.enum_types = {}
ADDRESSBOOK.fields = {ADDRESSBOOK_PERSON_FIELD}
ADDRESSBOOK.is_extendable = false
ADDRESSBOOK.extensions = {}

AddressBook = protobuf.Message(ADDRESSBOOK)
Person = protobuf.Message(PERSON)
Person.PhoneNumber = protobuf.Message(PERSON_PHONENUMBER)

